### PR TITLE
Upgrade all of packages in pubspec.yml

### PR DESCRIPTION
**Pull request by ngquangan**
- Update the packages used in the project to the latest version
- Update `dart_openai` to v1.9.1 and update breaking changes
- Apply flutter_env to store OPENAI_CHATGPT_TOKEN

### CODE REVIEW

**Review by caocuong2404 — APPROVED** [review]
Ok

**Review by lambui09 — COMMENTED** [review]
Pls rename .env.example to .env. Many thanks.

**Comment by gotecq-annguyen** [comment]
No, .env file must be add to .gitignore by default

**Comment by lambui09** [comment]
Yup, I understand, Many thanks.

**Comment by wewehao** [comment]
This is very useful, thanks a lot! ! ! @ngquangan

**Comment by ngquangan** [comment]
You're welcome.

**Pull request merged**
